// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcsuzqdammcaagegismr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhjc3V6cWRhbW1jYWFnZWdpc21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTU1NzAsImV4cCI6MjA3Mzg3MTU3MH0.cCXmz8bpHxIvQD7CMfShl19ZsaVy__ESUXADnjAZNps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});